### ISSUE TITLE
Rx 'via

### ISSUE THREAD

**Issue by gchiu** [gchiu/midcentral#3]
>> rx 'via
loaded off local storage
** Script Error: null? needs optional as ^META for ~ isotope
** Where: rx main
** Near: [*** switch drug data ** [
    print spaced ["Drug" drug "no...
** File: https://raw.githubusercontent.com/gchiu/midcentral/main/main.reb
** Line: 376

**Comment by hostilefork** [comment]
if null? result: switch drug data [; data comes from import link
            <print statements>
        ] else [
            if <condition> [<body>]
        ]

Your NULL? is operating on the totality of that expression.  So it's like you said:

        if null? ( result: switch drug data [ ; data comes from import link
            <print statements>
        ] else [
            if <condition> [<body>]
        ] )

What you intend here is:

        if (null? result: switch drug data) [ ; data comes from import link
            <print statements>
        ] else [
            if <condition> [<body>]
        ]

You could write that as:

        result: switch drug data then [ ; data comes from import link
            <print statements>
        ] else [
            if <condition> [<body>]
        ]

**Comment by gchiu** [comment]
fixed in [07c62da](https://github.com/gchiu/midcentral/commit/07c62da93dd1bc83c967e6fa6a91b47c9d9e7726)
