### ISSUE TITLE
rx 'd*

### ISSUE THREAD

**Issue by gchiu** [gchiu/midcentral#4]
No d drug page

>> rx 'd*
** Script Error: Invalid use of ~ isotope
** Where: try exists? rx main
** Near: [*** decay attempt [query target] ** 'type]
** File: -tmp-boot-
** Line: 4786

**Comment by hostilefork** [comment]
Do you need help looking into this?

**Comment by gchiu** [comment]
same as #3.  Fixed in [07c62da](https://github.com/gchiu/midcentral/commit/07c62da93dd1bc83c967e6fa6a91b47c9d9e7726)
